version: '3'

services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - 9000:9000
    networks:
      - sonar

  sonarqube_scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: sonarqube_scanner
    environment:
      SONAR_HOST_URL: http://##:9000/
      SONAR_LOGIN: ##
    volumes:
      - ./:/usr/src
    networks:
      - sonar

networks:
  sonar:

# To get ip of the sonarqube server run:
# docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' sonarqube
