# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Merge to master

on:
  push:
    branches:
      - master

jobs:
  update_to_the_latest_version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]

    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Generate coverage label
        run: |
          coverage run -m unittest discover -s tests -t ${PWD}
          coverage-badge -o ./coverage.svg
      - name: Push new coverage label
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_SECRET }}
          gist_id: 3f54787a495dfd8a05072c1eb12f9da3
          gist_file_name: coverage.svg
          file_path: ./coverage.svg
