name: Test new code

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  lint_and_unittest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Lint with isort
      run : isort ./algo_profiler
    - name: Lint with black
      run: black ./algo_profiler
    - name: Lint with flake8
      run: flake8 --max-line-length 90 ./algo_profiler
    - name: Tests
      run: python -m unittest discover -v -s tests -t ${PWD}
